export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER_ACCOUNT_DATA = 'FETCH_USER_ACCOUNT_DATA';

export const DELETE_USER_ACCOUNT = 'DELETE_USER_ACCOUNT';
export const DELETE_USER_TASK = 'DELETE_USER_TASK';
